# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(351, 429)
        self.label_title = QtWidgets.QLabel(parent=Form)
        self.label_title.setGeometry(QtCore.QRect(150, 30, 70, 16))
        self.label_title.setObjectName("label_title")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(110, 110, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButtonJane = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonJane.setGeometry(QtCore.QRect(10, 20, 95, 20))
        self.radioButtonJane.setObjectName("radioButtonJane")
        self.radioButtonJohn = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButtonJohn.setGeometry(QtCore.QRect(10, 50, 95, 20))
        self.radioButtonJohn.setObjectName("radioButtonJohn")
        self.id_input = QtWidgets.QPlainTextEdit(parent=Form)
        self.id_input.setGeometry(QtCore.QRect(120, 60, 104, 31))
        self.id_input.setObjectName("id_input")
        self.submit_button = QtWidgets.QPushButton(parent=Form)
        self.submit_button.setGeometry(QtCore.QRect(120, 210, 93, 28))
        self.submit_button.setObjectName("submit_button")
        self.label_input = QtWidgets.QLabel(parent=Form)
        self.label_input.setGeometry(QtCore.QRect(50, 70, 55, 16))
        self.label_input.setObjectName("label_input")
        self.label_check = QtWidgets.QLabel(parent=Form)
        self.label_check.setGeometry(QtCore.QRect(70, 260, 201, 41))
        self.label_check.setText("")
        self.label_check.setObjectName("label_check")
        self.label_johncount = QtWidgets.QLabel(parent=Form)
        self.label_johncount.setGeometry(QtCore.QRect(70, 330, 91, 41))
        self.label_johncount.setObjectName("label_johncount")
        self.label_janecount = QtWidgets.QLabel(parent=Form)
        self.label_janecount.setGeometry(QtCore.QRect(200, 330, 91, 41))
        self.label_janecount.setObjectName("label_janecount")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_title.setText(_translate("Form", "Vote Menu"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.radioButtonJane.setText(_translate("Form", "Jane"))
        self.radioButtonJohn.setText(_translate("Form", "John"))
        self.submit_button.setText(_translate("Form", "Submit"))
        self.label_input.setText(_translate("Form", "Input ID:"))
        self.label_johncount.setText(_translate("Form", "John Count:"))
        self.label_janecount.setText(_translate("Form", "Jane Count:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
